instance-id: ${spring.application.name}-${random.uuid}

spring:
  application:
    name: docker-web-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    hikari:
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
  jooq:
    sql-dialect: mysql
  mvc:
    favicon:
      enabled: false

logging:
  level:
    com.example.docker.helloworld: DEBUG
    org.jooq: DEBUG
  path: logs/${spring.application.name}

management:
  context-path: /manage
  security:
    enabled: false