version: '2'
services:
  web:
    image: harbor.eekui.group/demo/docker-helloworld:0.0.1-SNAPSHOT
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  lb:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 7070:7070/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
